name: walk
description: A new Flutter project.
publish_to: 'none'
version: 0.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.7.3

flutter:
  assets:
    - assets/images/sprite_single.png
    - assets/images/background.jpg
    - assets/images/star.png
